name: finrubert
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter>=1.0.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - nltk>=3.6
  - tqdm>=4.60.0
  - ipykernel>=6.0.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - datasets>=2.0.0
    - accelerate>=0.20.0
    - evaluate>=0.4.0
    - textblob>=0.17.0
    - razdel>=0.5.0
    - pymorphy2>=0.9.0
    - pymorphy2-dicts-ru>=2.4.0
    - spacy>=3.4.0
    - flask>=2.0.0
    - flask-cors>=3.0.0
    - requests>=2.28.0
    - beautifulsoup4>=4.11.0
    - lxml>=4.9.0
    - scrapy>=2.6.0